// Code generated by mkpreempt.go; DO NOT EDIT.

//go:build wasm || wasm32

#include "go_asm.h"
#include "textflag.h"

TEXT ·asyncPreempt(SB),NOSPLIT|NOFRAME,$0-0
	// No async preemption on wasm
	UNDEF
